# Generated by Django 5.1 on 2024-08-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='DF-00000', max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
